name: Broadcaster
author: imwood04
api: [3.0.0]
version: 1.0
main: imwood04\Main
website: https://nagames.herokuapp.com , https://github.com/imwood04
commands:
  fly:
    description: Allows youto fly
    permission: imwood04.fly
  oof:
    description: Says "Get OOFED on..."
    permission: imwood04.oof
  broadcast:
    description: Sends BroadCast.
    permission: imwood04.bc
    aliases:
      - bc

permissions:
  imwood04.fly:
    description: Gives perms to use /fly
    default: op
  imwood04.oof:
    description: Gives perms to use /oof
    default: op
  broadcast.cmd:
    description: Allows Use of /broadcast or /bc.
    default: op